### PR TITLE
Fixed PKGDEST via config file.

### PR DESCRIPTION
**Pull request by akurei**
Okay, I think I did it!
As you wished the PKGDEST it is now realized via the config file.

### CODE REVIEW

**Comment by akurei** [comment]
Is something wrong with the patch? It is two weeks since I posted it here and since then I have not gotten an answer.

**Comment by graysky2** [comment]
Sorry, I have been distracted and forgot about your PR.

**Comment by akurei** [comment]
I will look into it.

**Comment by akurei** [comment]
Unfortunately I still haven't had the time and need to look into this issue yet. Consider it on ice indefinitely. Sorry.

**Comment by graysky2** [comment]
OK

**Pull request closed without merging**
